# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65bad28bcf4d608cb9cc166262084ac24099ecba95c4df18683b39e57f80062eed035428e233ca3d17c1b60386ca04d9a8e8280eea34b30eaf58136a355c987a

test:
  secret_key_base: 7a5d6310bc237536cce1f086ec393288df4a5fbedf85879ae2c9505d75057631fe5544fce0b22f79125aa82f9100c040f7b4c87f7d8c0a11b30b1c5dc0b446af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
